using System.Globalization;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Xml.Linq;
using FullWorth.Backend.Data;
using FullWorth.Backend.Modules.Audit;
using FullWorth.Backend.Modules.Merchants;
using FullWorth.Backend.Modules.Transactions;
using FullWorth.Backend.Security;
using Microsoft.EntityFrameworkCore;

namespace FullWorth.Backend.Modules.Parity;

public sealed record ImportCommitWrite(Guid AccountId,IReadOnlyList<Guid>? CandidateIds=null);

public static class ImportParityEndpoints
{
    private const long MaxUploadBytes=25L*1024*1024;
    public static IEndpointRouteBuilder MapImportParityEndpoints(this IEndpointRouteBuilder app)
    {
        var group=app.MapGroup("/api/import-jobs").WithTags("Import");
        group.MapPost("/upload",Upload);
        group.MapGet("/",ListJobs);
        group.MapGet("/{id:guid}",GetJob);
        group.MapGet("/{id:guid}/candidates",GetCandidates);
        group.MapPost("/{id:guid}/commit",Commit);
        group.MapPost("/{id:guid}/cancel",Cancel);
        return app;
    }

    private static async Task<IResult> Upload(Guid fullWorthSpaceId,HttpRequest request,CurrentUserContext currentUser,FullWorthDbContext db,AuditService audit,CancellationToken ct)
    {
        var uid=currentUser.RequireUserId();if(!await ParitySql.IsMemberAsync(db,uid,fullWorthSpaceId,ct))return Results.NotFound();if(!request.HasFormContentType)return Results.BadRequest(new{error="Expected multipart/form-data."});var form=await request.ReadFormAsync(ct);var file=form.Files.GetFile("file");if(file is null||file.Length==0)return Results.BadRequest(new{error="No file uploaded."});if(file.Length>MaxUploadBytes)return Results.BadRequest(new{error="Maximum file size is 25 MB."});var ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(ext is not(".csv" or ".xlsx"))return Results.BadRequest(new{error="Supported formats are CSV and XLSX."});
        await using var ms=new MemoryStream(checked((int)file.Length));await file.CopyToAsync(ms,ct);var bytes=ms.ToArray();var sha=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();List<Dictionary<string,string>> rows;try{rows=ext==".csv"?ParseCsv(bytes):ParseXlsx(bytes);}catch(Exception e) when(e is InvalidDataException or FormatException){return Results.BadRequest(new{error=e.Message});}if(rows.Count==0)return Results.BadRequest(new{error="No data rows found."});
        var mapping=DetectMapping(rows[0].Keys);if(mapping.Date is null||mapping.Amount is null)return Results.BadRequest(new{error="Could not detect date and amount columns. Rename columns or use common names such as Date/Datum and Amount/Betrag."});var jobId=Guid.NewGuid();var now=DateTimeOffset.UtcNow;var candidates=new List<Candidate>();var errors=0;
        for(var i=0;i<rows.Count;i++){var row=rows[i];try{var date=ParseDate(row.GetValueOrDefault(mapping.Date));var amount=ParseAmount(row.GetValueOrDefault(mapping.Amount));var currency=NormalizeCurrency(mapping.Currency is null?null:row.GetValueOrDefault(mapping.Currency));var party=mapping.Counterparty is null?null:Clean(row.GetValueOrDefault(mapping.Counterparty));var description=mapping.Description is null?null:Clean(row.GetValueOrDefault(mapping.Description));var account=mapping.Account is null?null:Clean(row.GetValueOrDefault(mapping.Account));var external=mapping.ExternalKey is null?null:Clean(row.GetValueOrDefault(mapping.ExternalKey));var fingerprint=Fingerprint(date,amount,currency,party,description,external);candidates.Add(new(Guid.NewGuid(),account,date,amount,currency,party,description,mapping.Category is null?null:Clean(row.GetValueOrDefault(mapping.Category)),external,fingerprint,"ready",null));}catch(Exception e){errors++;candidates.Add(new(Guid.NewGuid(),null,null,0,"EUR",null,null,null,null,Fingerprint(null,0,"EUR",null,$"row-{i}",null),"error",e.Message));}}
        var connection=await ParitySql.OpenAsync(db,ct);await using var tx=await db.Database.BeginTransactionAsync(ct);await using(var job=ParitySql.Command(connection,"INSERT INTO \"ImportJobs\" (\"Id\",\"FullWorthSpaceId\",\"UserId\",\"FileName\",\"FileSha256\",\"AdapterKey\",\"Status\",\"SourceRowCount\",\"ReadyCount\",\"DuplicateCount\",\"ImportedCount\",\"ErrorCount\",\"CreatedAt\",\"UpdatedAt\") VALUES (@id,@space,@uid,@name,@sha,@adapter,@status,@source,@ready,0,0,@errors,@now,@now)",("@id",jobId),("@space",fullWorthSpaceId),("@uid",uid),("@name",Path.GetFileName(file.FileName)),("@sha",sha),("@adapter",ext==".csv"?"generic_csv":"generic_xlsx"),("@status",errors==candidates.Count?"failed":"ready"),("@source",candidates.Count),("@ready",candidates.Count-errors),("@errors",errors),("@now",now)))await job.ExecuteNonQueryAsync(ct);
        foreach(var c in candidates){await using var cmd=ParitySql.Command(connection,"""
INSERT INTO "ImportCandidates" ("Id","ImportJobId","SourceAccount","BookingDate","Amount","Currency","Counterparty","Description","CategoryText","ExternalKey","RowFingerprint","DuplicateStatus","ValidationStatus","ValidationError") VALUES (@id,@job,@account,@date,@amount,@currency,@party,@description,@category,@external,@fingerprint,'new',@status,@error)
""",("@id",c.Id),("@job",jobId),("@account",c.SourceAccount),("@date",c.Date),("@amount",c.Amount),("@currency",c.Currency),("@party",c.Counterparty),("@description",c.Description),("@category",c.Category),("@external",c.ExternalKey),("@fingerprint",c.Fingerprint),("@status",c.Status),("@error",c.Error));await cmd.ExecuteNonQueryAsync(ct);}audit.Record(fullWorthSpaceId,uid,"import.uploaded","ImportJob",jobId);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Results.Ok(new{jobId,fileName=file.FileName,adapter=ext==".csv"?"generic_csv":"generic_xlsx",sourceRows=candidates.Count,ready=candidates.Count-errors,errors,mapping});
    }

    private static async Task<IResult> ListJobs(Guid fullWorthSpaceId,CurrentUserContext currentUser,FullWorthDbContext db,CancellationToken ct){var uid=currentUser.RequireUserId();if(!await ParitySql.IsMemberAsync(db,uid,fullWorthSpaceId,ct))return Results.NotFound();var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"SELECT \"Id\",\"FileName\",\"AdapterKey\",\"Status\",\"SourceRowCount\",\"ReadyCount\",\"DuplicateCount\",\"ImportedCount\",\"ErrorCount\",\"CreatedAt\",\"CompletedAt\" FROM \"ImportJobs\" WHERE \"FullWorthSpaceId\"=@space AND \"UserId\"=@uid ORDER BY \"CreatedAt\" DESC",("@space",fullWorthSpaceId),("@uid",uid));await using var r=await cmd.ExecuteReaderAsync(ct);var rows=new List<object>();while(await r.ReadAsync(ct))rows.Add(JobRow(r));return Results.Ok(rows);}
    private static async Task<IResult> GetJob(Guid id,Guid fullWorthSpaceId,CurrentUserContext currentUser,FullWorthDbContext db,CancellationToken ct){var uid=currentUser.RequireUserId();var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"SELECT \"Id\",\"FileName\",\"AdapterKey\",\"Status\",\"SourceRowCount\",\"ReadyCount\",\"DuplicateCount\",\"ImportedCount\",\"ErrorCount\",\"CreatedAt\",\"CompletedAt\" FROM \"ImportJobs\" WHERE \"Id\"=@id AND \"FullWorthSpaceId\"=@space AND \"UserId\"=@uid",("@id",id),("@space",fullWorthSpaceId),("@uid",uid));await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Results.Ok(JobRow(r)):Results.NotFound();}
    private static async Task<IResult> GetCandidates(Guid id,Guid fullWorthSpaceId,CurrentUserContext currentUser,FullWorthDbContext db,CancellationToken ct){var uid=currentUser.RequireUserId();if(!await OwnJob(db,id,fullWorthSpaceId,uid,ct))return Results.NotFound();var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"SELECT \"Id\",\"SourceAccount\",\"BookingDate\",\"Amount\",\"Currency\",\"Counterparty\",\"Description\",\"CategoryText\",\"ExternalKey\",\"DuplicateStatus\",\"ValidationStatus\",\"ValidationError\" FROM \"ImportCandidates\" WHERE \"ImportJobId\"=@job ORDER BY \"BookingDate\",\"Id\"",("@job",id));await using var r=await cmd.ExecuteReaderAsync(ct);var rows=new List<object>();while(await r.ReadAsync(ct))rows.Add(new{id=ParitySql.Guid(r,"Id"),sourceAccount=ParitySql.NullableString(r,"SourceAccount"),bookingDate=ParitySql.NullableDate(r,"BookingDate"),amount=ParitySql.Decimal(r,"Amount"),currency=ParitySql.String(r,"Currency"),counterparty=ParitySql.NullableString(r,"Counterparty"),description=ParitySql.NullableString(r,"Description"),categoryText=ParitySql.NullableString(r,"CategoryText"),externalKey=ParitySql.NullableString(r,"ExternalKey"),duplicateStatus=ParitySql.String(r,"DuplicateStatus"),validationStatus=ParitySql.String(r,"ValidationStatus"),validationError=ParitySql.NullableString(r,"ValidationError")});return Results.Ok(rows);}

    private static async Task<IResult> Commit(Guid id,Guid fullWorthSpaceId,ImportCommitWrite request,CurrentUserContext currentUser,FullWorthDbContext db,FieldCipher cipher,AuditService audit,CancellationToken ct)
    {
        var uid=currentUser.RequireUserId();if(!await OwnJob(db,id,fullWorthSpaceId,uid,ct))return Results.NotFound();var writable=await ParitySql.WritableAccountIdsAsync(db,uid,fullWorthSpaceId,ct);if(!writable.Contains(request.AccountId))return Results.StatusCode(403);var account=await db.Accounts.SingleAsync(x=>x.Id==request.AccountId,ct);var selected=request.CandidateIds?.ToHashSet();var candidates=await ReadCandidates(db,id,ct);if(selected is not null)candidates=candidates.Where(x=>selected.Contains(x.Id)).ToList();candidates=candidates.Where(x=>x.Status=="ready"&&x.Date.HasValue).ToList();var imported=0;var duplicates=0;await using var transaction=await db.Database.BeginTransactionAsync(ct);
        foreach(var c in candidates){var normalized=MerchantNormalization.Normalize(c.Counterparty);var exists=await db.Transactions.AsNoTracking().AnyAsync(t=>t.AccountId==account.Id&&(t.BookingDate??t.ValueDate)==c.Date&&t.Amount==c.Amount&&t.Currency==c.Currency&&t.NormalizedCounterparty==normalized,ct);if(exists){duplicates++;await MarkCandidate(db,c.Id,"duplicate",ct);continue;}var external=!string.IsNullOrWhiteSpace(c.ExternalKey)?$"import:{id:N}:{c.ExternalKey}":$"import:{id:N}:{c.Fingerprint}";if(await db.Transactions.AnyAsync(t=>t.AccountId==account.Id&&t.ExternalKey==external,ct)){duplicates++;await MarkCandidate(db,c.Id,"duplicate",ct);continue;}db.Transactions.Add(new FinanceTransaction{AccountId=account.Id,ExternalKey=external,Status="BOOK",BookingDate=c.Date,ValueDate=c.Date,Amount=c.Amount,Currency=c.Currency,Counterparty=c.Counterparty,NormalizedCounterparty=normalized,Description=c.Description,CategorizationSource="none",RawJson=cipher.Protect("{\"source\":\"generic-import\"}")??"{}",FirstSeenAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow});imported++;await MarkCandidate(db,c.Id,"imported",ct);}
        await db.SaveChangesAsync(ct);var conn=await ParitySql.OpenAsync(db,ct);await using(var cmd=ParitySql.Command(conn,"UPDATE \"ImportJobs\" SET \"Status\"='completed',\"ImportedCount\"=@imported,\"DuplicateCount\"=@duplicates,\"UpdatedAt\"=@now,\"CompletedAt\"=@now WHERE \"Id\"=@id",("@imported",imported),("@duplicates",duplicates),("@now",DateTimeOffset.UtcNow),("@id",id)))await cmd.ExecuteNonQueryAsync(ct);audit.Record(fullWorthSpaceId,uid,"import.completed","ImportJob",id);await db.SaveChangesAsync(ct);await transaction.CommitAsync(ct);return Results.Ok(new{imported,duplicates,total=candidates.Count});
    }

    private static async Task<IResult> Cancel(Guid id,Guid fullWorthSpaceId,CurrentUserContext currentUser,FullWorthDbContext db,AuditService audit,CancellationToken ct){var uid=currentUser.RequireUserId();if(!await OwnJob(db,id,fullWorthSpaceId,uid,ct))return Results.NotFound();var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"UPDATE \"ImportJobs\" SET \"Status\"='cancelled',\"UpdatedAt\"=@now WHERE \"Id\"=@id AND \"Status\" NOT IN ('completed','cancelled')",("@now",DateTimeOffset.UtcNow),("@id",id));await cmd.ExecuteNonQueryAsync(ct);audit.Record(fullWorthSpaceId,uid,"import.cancelled","ImportJob",id);await db.SaveChangesAsync(ct);return Results.NoContent();}

    private sealed record Mapping(string? Date,string? Amount,string? Currency,string? Counterparty,string? Description,string? Account,string? Category,string? ExternalKey);
    private sealed record Candidate(Guid Id,string? SourceAccount,DateOnly? Date,decimal Amount,string Currency,string? Counterparty,string? Description,string? Category,string? ExternalKey,string Fingerprint,string Status,string? Error);
    private static Mapping DetectMapping(IEnumerable<string> headers){var h=headers.ToArray();string? Find(params string[] names)=>h.FirstOrDefault(x=>names.Any(n=>string.Equals(Norm(x),Norm(n),StringComparison.OrdinalIgnoreCase)));return new(Find("date","datum","booking date","buchungsdatum"),Find("amount","betrag","value","umsatz"),Find("currency","währung","waehrung"),Find("counterparty","empfänger","empfaenger","payee","merchant","gegenpartei"),Find("description","verwendungszweck","text","purpose","memo"),Find("account","konto","account name","referenzkonto"),Find("category","kategorie"),Find("id","booking id","transaction id","buchungs-id"));}
    private static string Norm(string value)=>new(value.Trim().ToLowerInvariant().Where(char.IsLetterOrDigit).ToArray());
    private static string? Clean(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
    private static string NormalizeCurrency(string? v){var s=Clean(v)?.ToUpperInvariant();return s is{Length:3}?s:"EUR";}
    private static DateOnly ParseDate(string? value){if(string.IsNullOrWhiteSpace(value))throw new FormatException("Date is missing.");var formats=new[]{"yyyy-MM-dd","dd.MM.yyyy","d.M.yyyy","dd/MM/yyyy","MM/dd/yyyy"};foreach(var f in formats)if(DateOnly.TryParseExact(value.Trim(),f,CultureInfo.InvariantCulture,DateTimeStyles.None,out var d))return d;if(DateOnly.TryParse(value,CultureInfo.CurrentCulture,out var parsed))return parsed;throw new FormatException($"Invalid date '{value}'.");}
    private static decimal ParseAmount(string? value){if(string.IsNullOrWhiteSpace(value))throw new FormatException("Amount is missing.");var s=value.Trim().Replace("€","").Replace(" ","");if(decimal.TryParse(s,NumberStyles.Number|NumberStyles.AllowLeadingSign,CultureInfo.GetCultureInfo("de-DE"),out var de))return de;if(decimal.TryParse(s,NumberStyles.Number|NumberStyles.AllowLeadingSign,CultureInfo.InvariantCulture,out var inv))return inv;throw new FormatException($"Invalid amount '{value}'.");}
    private static string Fingerprint(DateOnly? date,decimal amount,string currency,string? party,string? desc,string? external)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{date:yyyy-MM-dd}|{amount}|{currency}|{party}|{desc}|{external}"))).ToLowerInvariant();

    private static List<Dictionary<string,string>> ParseCsv(byte[] bytes){var text=Encoding.UTF8.GetString(bytes);var lines=SplitCsvRecords(text);if(lines.Count<2)return[];var delimiter=GuessDelimiter(lines[0]);var header=ParseCsvLine(lines[0],delimiter);var result=new List<Dictionary<string,string>>();foreach(var line in lines.Skip(1)){if(string.IsNullOrWhiteSpace(line))continue;var cells=ParseCsvLine(line,delimiter);var row=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<header.Count;i++)row[header[i]]=i<cells.Count?cells[i]:"";result.Add(row);}return result;}
    private static char GuessDelimiter(string line){var choices=new[]{';',',','\t'};return choices.OrderByDescending(c=>line.Count(x=>x==c)).First();}
    private static List<string> SplitCsvRecords(string text){var rows=new List<string>();var sb=new StringBuilder();var quoted=false;for(var i=0;i<text.Length;i++){var ch=text[i];if(ch=='\"'){quoted=!quoted;sb.Append(ch);}else if((ch=='\n'||ch=='\r')&&!quoted){if(ch=='\r'&&i+1<text.Length&&text[i+1]=='\n')i++;rows.Add(sb.ToString());sb.Clear();}else sb.Append(ch);}if(sb.Length>0)rows.Add(sb.ToString());return rows;}
    private static List<string> ParseCsvLine(string line,char delimiter){var cells=new List<string>();var sb=new StringBuilder();var quoted=false;for(var i=0;i<line.Length;i++){var ch=line[i];if(ch=='\"'){if(quoted&&i+1<line.Length&&line[i+1]=='\"'){sb.Append('\"');i++;}else quoted=!quoted;}else if(ch==delimiter&&!quoted){cells.Add(sb.ToString().Trim());sb.Clear();}else sb.Append(ch);}cells.Add(sb.ToString().Trim());return cells;}

    private static List<Dictionary<string,string>> ParseXlsx(byte[] bytes){using var ms=new MemoryStream(bytes);using var zip=new ZipArchive(ms,ZipArchiveMode.Read);var shared=new List<string>();var sharedEntry=zip.GetEntry("xl/sharedStrings.xml");if(sharedEntry is not null){using var s=sharedEntry.Open();var doc=XDocument.Load(s);XNamespace ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";shared=doc.Descendants(ns+"si").Select(si=>string.Concat(si.Descendants(ns+"t").Select(t=>t.Value))).ToList();}var sheet=zip.GetEntry("xl/worksheets/sheet1.xml")??throw new InvalidDataException("Workbook has no first worksheet.");using var stream=sheet.Open();var x=XDocument.Load(stream);XNamespace n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";var rawRows=new List<List<string>>();foreach(var row in x.Descendants(n+"row")){var cells=new SortedDictionary<int,string>();foreach(var cell in row.Elements(n+"c")){var reference=(string?)cell.Attribute("r")??"A1";var col=ColumnIndex(reference);var type=(string?)cell.Attribute("t");var value=cell.Element(n+"v")?.Value??cell.Element(n+"is")?.Element(n+"t")?.Value??"";if(type=="s"&&int.TryParse(value,out var si)&&si>=0&&si<shared.Count)value=shared[si];cells[col]=value;}var max=cells.Count==0?0:cells.Keys.Max();var arr=new List<string>();for(var i=0;i<=max;i++)arr.Add(cells.GetValueOrDefault(i,"") );rawRows.Add(arr);}if(rawRows.Count<2)return[];var headers=rawRows[0];var result=new List<Dictionary<string,string>>();foreach(var cells in rawRows.Skip(1)){var row=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<headers.Count;i++)row[headers[i]]=i<cells.Count?cells[i]:"";result.Add(row);}return result;}
    private static int ColumnIndex(string reference){var letters=new string(reference.TakeWhile(char.IsLetter).ToArray()).ToUpperInvariant();var result=0;foreach(var c in letters)result=result*26+(c-'A'+1);return result-1;}

    private static object JobRow(System.Data.Common.DbDataReader r)=>new{id=ParitySql.Guid(r,"Id"),fileName=ParitySql.String(r,"FileName"),adapterKey=ParitySql.String(r,"AdapterKey"),status=ParitySql.String(r,"Status"),sourceRowCount=ParitySql.Int(r,"SourceRowCount"),readyCount=ParitySql.Int(r,"ReadyCount"),duplicateCount=ParitySql.Int(r,"DuplicateCount"),importedCount=ParitySql.Int(r,"ImportedCount"),errorCount=ParitySql.Int(r,"ErrorCount"),createdAt=ParitySql.Timestamp(r,"CreatedAt"),completedAt=ParitySql.NullableTimestamp(r,"CompletedAt")};
    private static async Task<bool> OwnJob(FullWorthDbContext db,Guid id,Guid space,Guid uid,CancellationToken ct){var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"SELECT 1 FROM \"ImportJobs\" WHERE \"Id\"=@id AND \"FullWorthSpaceId\"=@space AND \"UserId\"=@uid",("@id",id),("@space",space),("@uid",uid));return await cmd.ExecuteScalarAsync(ct) is not null;}
    private static async Task<List<Candidate>> ReadCandidates(FullWorthDbContext db,Guid job,CancellationToken ct){var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"SELECT \"Id\",\"SourceAccount\",\"BookingDate\",\"Amount\",\"Currency\",\"Counterparty\",\"Description\",\"CategoryText\",\"ExternalKey\",\"RowFingerprint\",\"ValidationStatus\",\"ValidationError\" FROM \"ImportCandidates\" WHERE \"ImportJobId\"=@job",("@job",job));await using var r=await cmd.ExecuteReaderAsync(ct);var rows=new List<Candidate>();while(await r.ReadAsync(ct))rows.Add(new(ParitySql.Guid(r,"Id"),ParitySql.NullableString(r,"SourceAccount"),ParitySql.NullableDate(r,"BookingDate"),ParitySql.Decimal(r,"Amount"),ParitySql.String(r,"Currency"),ParitySql.NullableString(r,"Counterparty"),ParitySql.NullableString(r,"Description"),ParitySql.NullableString(r,"CategoryText"),ParitySql.NullableString(r,"ExternalKey"),ParitySql.String(r,"RowFingerprint"),ParitySql.String(r,"ValidationStatus"),ParitySql.NullableString(r,"ValidationError")));return rows;}
    private static async Task MarkCandidate(FullWorthDbContext db,Guid id,string status,CancellationToken ct){var c=await ParitySql.OpenAsync(db,ct);await using var cmd=ParitySql.Command(c,"UPDATE \"ImportCandidates\" SET \"DuplicateStatus\"=@status WHERE \"Id\"=@id",("@status",status),("@id",id));await cmd.ExecuteNonQueryAsync(ct);}
}
