// <auto-generated />
using FullWorth.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FullWorth.Web.Migrations;

[DbContext(typeof(AuthDbContext))]
[Migration("20260812235500_Passkeys")]
partial class Passkeys
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        AuthMigrationModelPasskeys.Build(modelBuilder);
#pragma warning restore 612, 618
    }
}
