// <auto-generated />
using System;
using FullWorth.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullWorth.Web.Migrations;

[DbContext(typeof(AuthDbContext))]
[Migration("20260812193000_InitialAuthSchema")]
partial class InitialAuthSchema
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        AuthMigrationModel.Build(modelBuilder);
#pragma warning restore 612, 618
    }
}
