// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelInstanceSettings
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelExternalAuth.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.InstanceSettings", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("ScopeKey").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<string>("PublicUrl").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("ScopeKey").IsUnique();
            b.ToTable("InstanceSettings", "auth");
        });
    }
}
