// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelAccountDeletion
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelPasskeys.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Auth.AuthUser", b =>
        {
            b.Property<DateTimeOffset?>("DeletionRequestedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("DeletionScheduledFor").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("DeletionLeaseUntil").HasColumnType("timestamp with time zone");
            b.Property<string>("DeletionLastError").HasMaxLength(120).HasColumnType("character varying(120)");
            b.HasIndex("DeletionScheduledFor").HasDatabaseName("DeletionScheduledForIndex");
        });
    }
}
