// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelAdmin
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelAccountDeletion.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Auth.AuthUser", b =>
        {
            b.Property<bool>("IsAdmin").HasColumnType("boolean");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.AdminAuditEvent", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<Guid>("ActorAuthUserId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Outcome").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<Guid?>("TargetAuthUserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("OccurredAt");
            b.HasIndex("TargetAuthUserId");
            b.ToTable("AdminAuditEvents", "auth");
        });
    }
}
