// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelPasskeys
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModel.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Auth.AuthUser", b =>
        {
            b.Property<bool>("IsDisabled").HasColumnType("boolean");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Sessions.UserSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("AbsoluteExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("DeviceName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("SecurityStampAtIssue").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");
            b.HasKey("Id");
            b.HasIndex("AbsoluteExpiresAt");
            b.HasIndex("AuthUserId");
            b.HasIndex("RevokedAt");
            b.ToTable("UserSessions", "auth");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Recovery.RecoveryCode", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<byte[]>("CodeHash").IsRequired().HasMaxLength(32).HasColumnType("bytea");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("UsedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("AuthUserId", "CodeHash").IsUnique();
            b.ToTable("RecoveryCodes", "auth", t => t.HasCheckConstraint("CK_RecoveryCodes_CodeHash_Length", "octet_length(\"CodeHash\") = 32"));
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Passkeys.PasskeyCredential", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<byte[]>("CredentialId").IsRequired().HasMaxLength(1024).HasColumnType("bytea");
            b.Property<byte[]>("PublicKey").IsRequired().HasMaxLength(4096).HasColumnType("bytea");
            b.Property<byte[]>("UserHandle").IsRequired().HasMaxLength(64).HasColumnType("bytea");
            b.Property<uint>("SignatureCounter").HasConversion<long>().HasColumnType("bigint");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("LastUsedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<Guid>("Aaguid").HasColumnType("uuid");
            b.Property<bool>("IsBackupEligible").HasColumnType("boolean");
            b.Property<bool>("IsBackedUp").HasColumnType("boolean");
            b.HasKey("Id");
            b.HasIndex("AuthUserId");
            b.HasIndex("CredentialId").IsUnique();
            b.ToTable("PasskeyCredentials", "auth");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Passkeys.PasskeyChallenge", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid?>("AuthUserId").HasColumnType("uuid");
            b.Property<int>("Type").HasColumnType("integer");
            b.Property<string>("OptionsJson").IsRequired().HasMaxLength(32768).HasColumnType("character varying(32768)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("ConsumedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("AuthUserId");
            b.HasIndex("Type", "ExpiresAt", "ConsumedAt");
            b.ToTable("PasskeyChallenges", "auth", t =>
            {
                t.HasCheckConstraint("CK_PasskeyChallenges_Type", "\"Type\" IN (1, 2)");
                t.HasCheckConstraint("CK_PasskeyChallenges_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");
                t.HasCheckConstraint("CK_PasskeyChallenges_ConsumedAt", "\"ConsumedAt\" IS NULL OR \"ConsumedAt\" >= \"CreatedAt\"");
            });
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Sessions.UserSession", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null).WithMany().HasForeignKey("AuthUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Recovery.RecoveryCode", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null).WithMany().HasForeignKey("AuthUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Passkeys.PasskeyCredential", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null).WithMany().HasForeignKey("AuthUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Passkeys.PasskeyChallenge", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null).WithMany().HasForeignKey("AuthUserId").OnDelete(DeleteBehavior.Cascade);
        });
    }
}
