// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelExternalAuth
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelAdmin.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.ExternalAuthSettings", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("ScopeKey").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<string>("GoogleClientId").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("GoogleClientSecretProtected").IsRequired().HasColumnType("text");
            b.Property<string>("AppleServiceId").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("AppleTeamId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("ApplePrivateKeyId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("ApplePrivateKeyProtected").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("ScopeKey").IsUnique();
            b.ToTable("ExternalAuthSettings", "auth");
        });
    }
}
