// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelCurrent
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModel.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Auth.AuthUser", b =>
        {
            b.Property<bool>("IsDisabled").HasColumnType("boolean");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Sessions.UserSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("AbsoluteExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("DeviceName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("SecurityStampAtIssue").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");

            b.HasKey("Id");
            b.HasIndex("AbsoluteExpiresAt");
            b.HasIndex("AuthUserId");
            b.HasIndex("RevokedAt");
            b.ToTable("UserSessions", "auth");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Recovery.RecoveryCode", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<byte[]>("CodeHash").IsRequired().HasMaxLength(32).HasColumnType("bytea");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("UsedAt").HasColumnType("timestamp with time zone");

            b.HasKey("Id");
            b.HasIndex("AuthUserId", "CodeHash").IsUnique();
            b.ToTable("RecoveryCodes", "auth", t =>
                t.HasCheckConstraint("CK_RecoveryCodes_CodeHash_Length", "octet_length(\"CodeHash\") = 32"));
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Sessions.UserSession", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("AuthUserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Recovery.RecoveryCode", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("AuthUserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
    }
}
