// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelInstanceConfiguration
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelInstanceSettings.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.InstanceConfigurationValue", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Value").IsRequired().HasColumnType("text");
            b.Property<bool>("IsProtected").HasColumnType("boolean");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("UpdatedByUserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("Key").IsUnique();
            b.ToTable("InstanceConfigurationValues", "auth");
        });
    }
}
