// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModelAdminVault
{
    public static void Build(ModelBuilder modelBuilder)
    {
        AuthMigrationModelInstanceConfiguration.Build(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.AdminElevation", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<Guid>("SessionId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<int>("RevealsUsed").HasColumnType("integer");
            b.Property<string>("Factor").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
            b.Property<string>("CodeHash").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("AuthUserId", "SessionId");
            b.ToTable("AdminElevations", "auth");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.AdminElevationLockout", b =>
        {
            b.Property<Guid>("AuthUserId").HasColumnType("uuid");
            b.Property<int>("Failures").HasColumnType("integer");
            b.Property<DateTimeOffset?>("LockedUntil").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("AuthUserId");
            b.ToTable("AdminElevationLockouts", "auth");
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.AdminElevation", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("AuthUserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("FullWorth.Web.Modules.Admin.AdminElevationLockout", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("AuthUserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
    }
}
