// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullWorth.Web.Migrations;

internal static class AuthMigrationModel
{
    public static void Build(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("auth")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FullWorth.Web.Modules.Auth.AuthUser", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<int>("AccessFailedCount").HasColumnType("integer");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            b.Property<Guid>("FinanceUserId").HasColumnType("uuid");
            b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedUserName").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<string>("PhoneNumber").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
            b.Property<string>("SecurityStamp").HasColumnType("text");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("UserName").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");

            b.HasKey("Id");
            b.HasIndex("FinanceUserId").IsUnique().HasDatabaseName("FinanceUserIdIndex");
            b.HasIndex("NormalizedEmail").IsUnique().HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            b.ToTable("AspNetUsers", "auth");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims", "auth");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.Property<string>("LoginProvider").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("ProviderKey").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("ProviderDisplayName").HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins", "auth");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<string>("LoginProvider").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Name").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Value").HasColumnType("text");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens", "auth");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.HasOne("FullWorth.Web.Modules.Auth.AuthUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
    }
}
