using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace FullWorth.Backend.Modules.Purchases;

public sealed record PurchaseWrite(
    Guid? TransactionId,
    string Source,
    string Merchant,
    string? ExternalOrderId,
    DateOnly? PurchaseDate,
    decimal TotalAmount,
    string Currency,
    string Status,
    string? SourceReference,
    string? Notes,
    Guid? MerchantId = null,
    string? MerchantRaw = null,
    TimeOnly? PurchaseTime = null,
    string? TimeZone = null,
    decimal? SubtotalAmount = null,
    decimal? DiscountAmount = null,
    decimal? DepositAmount = null,
    decimal? TaxAmount = null,
    decimal? TipAmount = null,
    decimal? ShippingAmount = null,
    decimal? FeeAmount = null,
    string? ReviewState = null,
    string? ReceiptNumber = null,
    string? InvoiceNumber = null,
    string? PaymentMethodText = null,
    bool? IsBookmarked = null,
    decimal? RoundingAmount = null);

public sealed record PurchaseItemWrite(
    Guid? CategoryId,
    string Name,
    string? Brand,
    string? Sku,
    string? Asin,
    decimal Quantity,
    decimal? UnitPrice,
    decimal TotalPrice,
    string Currency,
    string? Notes,
    Guid? ProductId = null,
    string? RawName = null,
    string? Barcode = null,
    string? QuantityUnit = null,
    decimal? PackageQuantity = null,
    string? PackageUnit = null,
    decimal? PackageCount = null,
    decimal? BaseUnitPrice = null,
    decimal? DiscountAmount = null,
    decimal? DepositAmount = null,
    decimal? TaxRate = null,
    decimal? TaxAmount = null,
    string? LineType = null,
    decimal? ExtractionConfidence = null,
    bool IsManuallyCorrected = false,
    bool TotalPriceOverridden = false,
    int? SortOrder = null,
    DateOnly? ReturnDeadline = null,
    DateOnly? WarrantyEnd = null,
    string? SerialNumber = null,
    decimal? OriginalUnitPrice = null,
    string? DiscountLabel = null);

public sealed record LinkPurchaseRequest(Guid TransactionId, decimal? Confidence);
