// <auto-generated />
using System;
using FullWorth.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullWorth.Backend.Migrations
{
    [DbContext(typeof(FullWorthDbContext))]
    [Migration("20260826222115_AddPushDevices")]
    partial class AddPushDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.AccountOwner", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId", "AccountId");

                    b.ToTable("AccountOwners", t =>
                        {
                            t.HasCheckConstraint("CK_AccountOwners_OwnershipType", "\"OwnershipType\" IN ('owner', 'viewer')");
                        });
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("BalanceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("ReferenceDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CapturedAt");

                    b.ToTable("BalanceSnapshots");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.FinanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .HasColumnType("text");

                    b.Property<Guid>("BankConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("IbanLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("IdentificationHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("Provider", "IdentificationHash");

                    b.HasIndex("FullWorthSpaceId", "Provider", "IdentificationHash")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("FullWorthSpaceId", "OccurredAt");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.BankConnections.BankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AuthorizationState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextSyncAllowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderSessionId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationState")
                        .IsUnique();

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("Provider", "ProviderSessionId")
                        .IsUnique();

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<bool>("CarryOver")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("IsActive", "CategoryId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Categories.CategorizationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("MarkAsTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchField")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("MerchantCategoryCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("StopProcessing")
                        .HasColumnType("boolean");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("Target", "IsEnabled", "Priority");

                    b.ToTable("CategorizationRules");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Categories.FinanceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("Key");

                    b.HasIndex("ParentId");

                    b.HasIndex("FullWorthSpaceId", "Key")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.PriceChanges.PriceChangeSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DetectedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("EvidenceTransactionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("OldAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("PercentChange")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EvidenceTransactionId");

                    b.ToTable("PriceChangeSuggestions");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.RecurringContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<bool>("AutoDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("IsActive", "NextDueDate");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.Review.DismissedContractCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId", "Counterparty", "Currency")
                        .IsUnique();

                    b.ToTable("DismissedContractCandidates");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FullWorthSpaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b21b1a4-0b7b-4ae1-93d0-b8d1f859e8a1"),
                            BaseCurrency = "EUR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Default",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpaceMember", b =>
                {
                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("FullWorthSpaceId", "UserId");

                    b.HasIndex("FullWorthSpaceId", "Role");

                    b.HasIndex("UserId", "FullWorthSpaceId");

                    b.ToTable("FullWorthSpaceMembers", t =>
                        {
                            t.HasCheckConstraint("CK_FullWorthSpaceMembers_Role", "\"Role\" IN ('owner', 'member')");
                        });
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Fees")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FixedTermMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NominalInterestRate")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("OriginalPrincipal")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FullWorthSpaceId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Merchants", (string)null);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Merchants.MerchantAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("FullWorthSpaceId", "NormalizedAlias")
                        .IsUnique();

                    b.ToTable("MerchantAliases", (string)null);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnnualGrowthRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ValuedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.Liability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RegularPayment")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.NetWorthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accounts")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("Assets")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Liabilities")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("NetWorth")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Date", "Currency");

                    b.HasIndex("FullWorthSpaceId", "UserId");

                    b.HasIndex("FullWorthSpaceId", "UserId", "Date", "Currency")
                        .IsUnique();

                    b.ToTable("NetWorthSnapshots");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FullWorthSpaceId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MatchConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ReceiptImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullWorthSpaceId");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Source", "ExternalOrderId");

                    b.HasIndex("FullWorthSpaceId", "Source", "ExternalOrderId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Brand")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CategorizationSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Sku")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Asin");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("Sku");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Push.PushDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FinanceUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FinanceUserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushDevices");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Transactions.FinanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<DateOnly?>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CategorizationSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Counterparty")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntryReference")
                        .HasColumnType("text");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantCategoryCode")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCounterparty")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TransferGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NormalizedCounterparty");

                    b.HasIndex("TransferGroupId");

                    b.HasIndex("AccountId", "ExternalKey")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Users.FullWorthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.AccountOwner", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Accounts.FinanceAccount", "Account")
                        .WithMany("Owners")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Users.FullWorthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.BalanceSnapshot", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Accounts.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.FinanceAccount", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.BankConnections.BankConnection", null)
                        .WithMany()
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.BankConnections.BankConnection", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Budgets.Budget", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Categories.CategorizationRule", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Categories.FinanceCategory", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.PriceChanges.PriceChangeSuggestion", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Contracts.RecurringContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Transactions.FinanceTransaction", "EvidenceTransaction")
                        .WithMany()
                        .HasForeignKey("EvidenceTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("EvidenceTransaction");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.RecurringContract", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Accounts.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.Review.DismissedContractCandidate", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpaceMember", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", "FullWorthSpace")
                        .WithMany("Members")
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Users.FullWorthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FullWorthSpace");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Loans.Loan", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Accounts.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Merchants.Merchant", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Merchants.MerchantAlias", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.Asset", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.Liability", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Portfolio.NetWorthSnapshot", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Users.FullWorthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.Purchase", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", null)
                        .WithMany()
                        .HasForeignKey("FullWorthSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Transactions.FinanceTransaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.PurchaseItem", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FullWorth.Backend.Modules.Purchases.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Push.PushDevice", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Users.FullWorthUser", null)
                        .WithMany()
                        .HasForeignKey("FinanceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Transactions.FinanceTransaction", b =>
                {
                    b.HasOne("FullWorth.Backend.Modules.Accounts.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullWorth.Backend.Modules.Categories.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.FinanceAccount", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.Purchase", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
