// <auto-generated />
using FullWorth.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FullWorth.Backend.Migrations;

[DbContext(typeof(FullWorthDbContext))]
partial class FullWorthDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        new AddNotificationDedups().BuildSnapshotBaseline(modelBuilder);
        FullWorthDbContextSnapshotDeltaV20260902.Apply(modelBuilder);
        EnableBankingProfilesSnapshot.Apply(modelBuilder);
        EnableBankingAccountIdentificationHashesSnapshot.Apply(modelBuilder);
        EnableBankingAccountMetadataSnapshot.Apply(modelBuilder);
        UserOnboardingSnapshot.Apply(modelBuilder);
        AccountDeletionSnapshot.Apply(modelBuilder);
        TransactionBalanceHistoryTrustSnapshot.Apply(modelBuilder);
        TransferDetectionIbanSnapshot.Apply(modelBuilder);
        BalanceProvenanceSnapshot.Apply(modelBuilder);
        AccountDuplicateLinkSnapshot.Apply(modelBuilder);
        OccupationalPensionSnapshot.Apply(modelBuilder);
        AssetValuationAsOfProvenanceSnapshot.Apply(modelBuilder);
        PensionDocumentExtractionSnapshot.Apply(modelBuilder);
        PensionAllocationDocumentSnapshot.Apply(modelBuilder);
        modelBuilder.Entity("FullWorth.Backend.Modules.Budgets.Budget", entity =>
        {
            entity.Property<bool>("CarryOverOverspend").HasColumnType("boolean");
        });
        modelBuilder.Entity("FullWorth.Backend.Modules.Contracts.RecurringContract", entity =>
        {
            // 20260911140000_ContractCountsAsFixedCost. Added with raw SQL, so the snapshot has to know
            // it or startup migration trips PendingModelChangesWarning.
            entity.Property<bool>("CountsAsFixedCost").HasColumnType("boolean");
            entity.Property<Guid?>("MergedIntoContractId").HasColumnType("uuid");
            entity.HasIndex("MergedIntoContractId");
            entity.HasOne("FullWorth.Backend.Modules.Contracts.RecurringContract", null)
                .WithMany()
                .HasForeignKey("MergedIntoContractId")
                .OnDelete(DeleteBehavior.Restrict);
        });
        modelBuilder.Entity("FullWorth.Backend.Modules.BankConnections.BankingInstanceSettings", entity =>
        {
            // 20260912130000_BankingInstanceSettings. Created with raw SQL, so the snapshot has to know
            // it or startup migration trips PendingModelChangesWarning.
            entity.Property<Guid>("Id").HasColumnType("uuid");
            entity.Property<string>("ScopeKey").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            entity.Property<string>("FinTsProductId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            entity.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            entity.HasKey("Id");
            entity.HasIndex("ScopeKey").IsUnique();
            entity.ToTable("BankingInstanceSettings");
        });

        modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.AccountGroup", entity =>
        {
            // 20260915200000_AccountGroupDefault. Rohes SQL, also muss der Snapshot es kennen.
            entity.Property<bool>("IsDefault").HasColumnType("boolean");
            entity.HasIndex("FullWorthSpaceId", "IsDefault");
        });

        modelBuilder.Entity("FullWorth.Backend.Modules.Accounts.FinanceAccount", entity =>
        {
            // 20260915190000_AccountProviderDisplayName. Rohes SQL, also muss der Snapshot dieselbe
            // Laenge nennen wie Migration und Entitaetskonfiguration.
            entity.Property<string>("ProviderDisplayName").HasMaxLength(200).HasColumnType("character varying(200)");
        });

        modelBuilder.Entity("FullWorth.Backend.Modules.Purchases.FinanceTag", entity =>
        {
            // 20260915170000_Collections. Rohes SQL, also muss der Snapshot es kennen - und dieselben
            // Laengen nennen wie die Datenannotationen an der Entitaet, sonst PendingModelChangesWarning.
            entity.Property<string>("Icon").HasMaxLength(64).HasColumnType("character varying(64)");
            entity.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)");
            entity.Property<DateOnly?>("StartDate").HasColumnType("date");
            entity.Property<DateOnly?>("EndDate").HasColumnType("date");
            entity.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
            entity.HasIndex("FullWorthSpaceId", "Status");
        });

        modelBuilder.Entity("FullWorth.Backend.Modules.FullWorthSpaces.FullWorthSpace", entity =>
        {
            // 20260915140000_DefaultCategoryLanguage. Raw SQL, also muss der Snapshot es kennen,
            // sonst faellt der Start ueber PendingModelChangesWarning.
            entity.Property<string>("DefaultCategoryLanguage").HasMaxLength(8).HasColumnType("character varying(8)");
            entity.Property<DateTimeOffset?>("DefaultCategoriesSeededAt").HasColumnType("timestamp with time zone");
        });

        modelBuilder.Entity("FullWorth.Backend.Security.InstallationEncryptionMarker", entity =>
        {
            // 20260912220000_InstallationEncryptionMarker. Raw SQL again, so the snapshot has to carry
            // it or startup migration trips PendingModelChangesWarning.
            entity.Property<Guid>("Id").HasColumnType("uuid");
            entity.Property<string>("ScopeKey").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            entity.Property<string>("KeyFingerprint").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            entity.Property<DateTimeOffset>("FirstSeenAt").HasColumnType("timestamp with time zone");
            entity.HasKey("Id");
            entity.HasIndex("ScopeKey").IsUnique();
            entity.ToTable("InstallationEncryptionMarkers");
        });
#pragma warning restore 612, 618
    }
}
