// <auto-generated />
using FullWorth.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FullWorth.Backend.Migrations;

[DbContext(typeof(FullWorthDbContext))]
partial class FullWorthDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        new AddNotificationDedups().BuildSnapshotBaseline(modelBuilder);
        FullWorthDbContextSnapshotDeltaV20260902.Apply(modelBuilder);
#pragma warning restore 612, 618
    }
}
